version: "3.9"

services:
  web:
    build:
      context: ./mail-indexer
      args:
        VITE_API_URL: $VITE_API_URL
    ports:
    - "80:8080"

  api:
    build:
      context: ./mail-indexer-api
      args:
        AUTH_USERNAME: $AUTH_USERNAME
        AUTH_PASSWORD: $AUTH_PASSWORD
        DB_PORT: $DB_PORT
    ports:
      - "8080:8080"
  zincsearch:
    image: public.ecr.aws/zinclabs/zinc:latest

    environment:
      - ZINC_FIRST_ADMIN_USER=${AUTH_USERNAME}
      - ZINC_FIRST_ADMIN_PASSWORD=${AUTH_PASSWORD}
      - ZINC_SERVER_PORT=${DB_PORT}
      - ZINC_DATA_PATH=/data
    ports:
      - ${DB_PORT}:${DB_PORT}

