version: "3.9"

services:
  zincsearch:
    image: public.ecr.aws/zinclabs/zinc:latest

    environment:
      - ZINC_FIRST_ADMIN_USER=${AUTH_USERNAME}
      - ZINC_FIRST_ADMIN_PASSWORD=${AUTH_PASSWORD}
      - ZINC_SERVER_PORT=${DB_PORT}
    ports:
      - ${DB_PORT}:${DB_PORT}
    container_name: zincsearch
  api:
    build:
      context: ./mail-indexer-api
      args:
        ZINC_URL: $ZINC_URL
        AUTH_USERNAME: $AUTH_USERNAME
        AUTH_PASSWORD: $AUTH_PASSWORD
        DB_PORT: $DB_PORT
    ports:
      - "8080:8080"
    container_name: api
    depends_on:
      - zincsearch
  web:
    build:
      context: ./mail-indexer
      args:
        VITE_API_URL: $VITE_API_URL
    ports:
      - "80:8080"
    container_name: web
    depends_on:
      - api

  
  

